---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  docker-secret-tool
  namespace: tools-test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  docker-secret-tool
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: docker-secret-tool
subjects:
  - kind: ServiceAccount
    name: docker-secret-tool
    namespace: tools-test