apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  docker-secret-tool
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
      - patch
      - update
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - mutatingWebhookconfigurations 
    verbs:
      - get  
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "certificates.k8s.io" 
    resources:
      - "certificatesigningrequests"
      - "certificatesigningrequests/status"
    verbs:
      - create
      - get
      - update
      - patch   