apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-secret-tool-config
  labels:
    app: docker-secret-tool
data:
  config.yaml: |
    watchNamespaces:
      - tool-test
    dockerSecretNames:
      - tpaas-itg
    setMethod: WebHook
    serviceName: docker-secret-tool-webhook
    autoTLS: true