apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-secret-tool-config
  labels:
    app: docker-secret-tool
data:
  config.yaml: |
    watchNamespaces:
      - tools-test
    dockerSecretNames:
      - docker-dev
    setMethod: WebHook
    serviceName: docker-secret-tool-webhook
